export const tagsList = [
    "Politics",
    "Travel",
    "World",
    "Investment",
    "Crime",
    "Business",
    "Education",
    "Romance",
    "Jobs/vacancies",
    "Space",
    "NASA",
    "Astrophysics",
    "Car Talk",
    "Properties",
    "Family",
    "Health",
    "Fashion",
    "Agriculture",
    "Computers",
    "Phones",
    "Graphics & Video",
    "Programming",
    "Technology Market",
    "Jokes and Comedy",
    "Literature",
    "Music/Radio",
    "Sport and Gaming",
    "Pets",
    "Autos",
    "NYSC",
    "Culture",
    "Religion",
    "Food",
    "Diaries",
    "Webmasters",
    "Art",
    "Finance",
  ];
  